import {
  BALANCE_ROUTES,
  EXCHANGE_RATE_ROUTES,
  PAYMENT_ROUTES,
  PAYOUT_ROUTES,
  TEST_WEBHOOK_ROUTES,
  TRANSFER_ROUTES,
  WALLET_ROUTES,
} from '../../controllers';

export const REST_API = {
  PAYMENT: {
    POST_CREATE: PAYMENT_ROUTES.POST_CREATE,
    POST_INFO: PAYMENT_ROUTES.POST_INFO,
    POST_LIST: PAYMENT_ROUTES.POST_LIST,
    POST_SERVICES: PAYMENT_ROUTES.POST_SERVICES,
    POST_RESEND: PAYMENT_ROUTES.POST_RESEND,
    POST_AML_LINKS: PAYMENT_ROUTES.POST_AML_LINKS,
    POST_REFUND: PAYMENT_ROUTES.POST_REFUND,
  },
  PAYOUT: {
    POST_CREATE: PAYOUT_ROUTES.POST_CREATE,
    POST_INFO: PAYOUT_ROUTES.POST_INFO,
    POST_LIST: PAYOUT_ROUTES.POST_LIST,
    POST_SERVICES: PAYOUT_ROUTES.POST_SERVICES,
    POST_CALCULATE: PAYOUT_ROUTES.POST_CALCULATE,
  },
  WALLET: {
    POST_CREATE: WALLET_ROUTES.POST_CREATE,
    POST_QR: WALLET_ROUTES.POST_QR,
    POST_BLOCK_ADDRESS: WALLET_ROUTES.POST_BLOCK_ADDRESS,
    POST_BLOCKED_ADDRESS_REFUND: WALLET_ROUTES.POST_BLOCKED_ADDRESS_REFUND,
  },
  TEST_WEBHOOK: {
    POST_PAYMENT: TEST_WEBHOOK_ROUTES.POST_PAYMENT,
    POST_WALLET: TEST_WEBHOOK_ROUTES.POST_WALLET,
  },
  TRANSFER: {
    POST_TO_PERSONAL: TRANSFER_ROUTES.POST_TO_PERSONAL,
    POST_TO_BUSINESS: TRANSFER_ROUTES.POST_TO_BUSINESS,
  },
  EXCHANGE_RATE: {
    GET_LIST: EXCHANGE_RATE_ROUTES.GET_LIST,
  },
  BALANCE: {
    POST_GET: BALANCE_ROUTES.POST_GET,
  },
} as const;
