import {
  BALANCE_ROUTES,
  PAYMENT_ROUTES,
  PAYOUT_ROUTES,
  WALLET_ROUTES,
} from '../../controllers';

export const REST_API = {
  PAYMENT: {
    POST_CREATE: PAYMENT_ROUTES.POST_CREATE,
    POST_INFO: PAYMENT_ROUTES.POST_INFO,
    POST_LIST: PAYMENT_ROUTES.POST_LIST,
    POST_SERVICES: PAYMENT_ROUTES.POST_SERVICES,
    POST_RESEND: PAYMENT_ROUTES.POST_RESEND,
  },
  PAYOUT: {
    POST_CREATE: PAYOUT_ROUTES.POST_CREATE,
    POST_INFO: PAYOUT_ROUTES.POST_INFO,
    POST_LIST: PAYOUT_ROUTES.POST_LIST,
    POST_SERVICES: PAYOUT_ROUTES.POST_SERVICES,
  },
  WALLET: {
    POST_CREATE: WALLET_ROUTES.POST_CREATE,
  },
  BALANCE: {
    POST_GET: BALANCE_ROUTES.POST_GET,
  },
} as const;
